name: CookieClicker
version: '5.0 - 1.20.6'
main: de.zillolp.cookieclicker.CookieClicker
api-version: 1.19
author: ZilloLP
softdepend:
  - Multiverse-Core
  - PlaceholderAPI
commands:
  cookieclicker:
    description: Manage CookieClicker
    usage: §7[§6CookieClicker§7] §cUse /cookieclicker help.